Updates to support Python3
TypeError: a bytes-like object is required, not 'str'

decode early

-    lines = r.content.strip().replace('}', '\n')
+    lines = r.content.decode('unicode-escape').strip(). replace('}', '\n')

TypeError: write() argument must be str, not bytes

write output as binary

-    with open (filename, 'w') as handle:
+    with open (filename, 'wb') as handle: